springdoc:
  api-docs:
    path: /v3/api-docs   # OpenAPI 문서를 제공하는 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
    display-request-duration: true
    operationsSorter: method

server:
  port: 8080

spring:
  profiles:
    active: test

jwt:
  secret-key: "b3f45e8893c24c6b8f7a9f292d7b3a8e9c12d9e8b2e34c6f8f7d9a9b2c3e4f5g"
