springdoc:
  api-docs:
    path: /v3/api-docs   # OpenAPI 문서를 제공하는 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
    display-request-duration: true
    operationsSorter: method

server:
  port: 8080

spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  data:
    redis:
      host: host.docker.internal
      port: 6379
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: PAYMENT-CONSUMER-GROUlP
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      topic:
        payment-success: payment-notification
        payment-fail: payment-notification.DLQ
        payment-fail-permanent: payment-notification.DLQ.permanent
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secret-key: "b3f45e8893c24c6b8f7a9f292d7b3a8e9c12d9e8b2e34c6f8f7d9a9b2c3e4f5g"

message:
  bot-token: "7571399816:AAHID_WyHT3TvUqh6F8nA8xQxXhyehnP8gw"
  chat-id: "5429089763"
  env: "[DEFAULT]"